using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using Mechanics_Assistant_Client.Forms;
using System.IO;
using System.Runtime.Serialization.Json;
using System.Runtime.Serialization;
using Mechanic_Assistant_Client.src;

namespace Mechanics_Assistant_Client
{
    /*
     * Storage class for the query data from the User
     */
    [DataContract]
    class MechanicsEntry
    {

        [DataMember]
        public string Model { get; set; }

        [DataMember]
        public string Make { get; set; }

        [DataMember]
        public string Complaint { get; set; }

        public MechanicsEntry(string make, string model, string complaint)
        {
            Make = make;
            Model = model;
            Complaint = complaint;
        }
    }

    /*
     * Storage class for the Problem generated by the ProblemPredictionProgram
     */
    [DataContract]
    public class ProblemStorage
    {
        [DataMember]
        public string Problem { get; set; }
        public ProblemStorage(string problem)
        {
            Problem = problem;
        }
    }

    static class Program
    {
        /*
         * opens the fie that was created by ProblemPredictionWrapper
         */
        public static void OpenOutfileStream(string fileName, out StreamWriter fileWriterOut)
        {
            try
            {
                fileWriterOut = new StreamWriter(fileName);
            } catch(FileNotFoundException)
            {
                throw new AccessViolationException("Could not access file " + fileName);
            }
        }

        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            bool ShouldQuery;
            QueryProcessingServerUtils.StartServer();
            //do while the User is signed in
            do
            {
                MechanicsAssistant MainForm = new MechanicsAssistant();
                Application.Run(MainForm);
                ShouldQuery = false;
                //if the query window passes control
                if (MainForm.ShouldQuery)
                {
                    string make = MainForm.GetMakeTextBoxValue();
                    string model = MainForm.GetModelTextBoxValue();
                    string complaint = MainForm.GetComplaintTextBoxValue();
                    List<string> predictedProblems = QueryProcessingServerUtils.ProcessQuery(make, model, complaint);
                    List<ProblemStorage> returnValues = new List<ProblemStorage>();
                    foreach (string s in predictedProblems)
                        returnValues.Add(new ProblemStorage(s));
                    MechanicsAssistantOutputForm outputForm = new MechanicsAssistantOutputForm();
                    outputForm.AddData(returnValues);
                    Application.Run(outputForm);
                    ShouldQuery = outputForm.ShouldQueryAgain;
                }
            } while (ShouldQuery);
            QueryProcessingServerUtils.CloseServer();
        }
    }
}
